name: Readme updater
on:
  schedule:
    # Runs every day at 9am UTC
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: install python dependencies
        run: |
          pip install -r requirements.txt
          python pubsub_fetcher.py
      - name: Creating the readme
        run: |
          name = cat "$(pubsubs.json)" | jq '.name' -C | more
          echo "Hello, my name is Abrahan Nevarez. I'm currently working on various projects, but my favorite is my pubsub site." > README.md
          echo "\nThe current sub available is: " >>  README.md
          echo "$name" >>  README.md
          cat pubsubs.json | jq '.image'
          cat pubsubs.json | jq '.last_on_sale'
          cat pubsubs.json | jq '.name'
          cat pubsubs.json | jq '.price'
          
      - name: Commit file changes
        run: |
            git config --global user.name 'zenith110'
            git config --global user.email ${{ secrets.EMAIL }}
            git add .
            git diff --quiet --cached || git commit -m "Update README" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
