name: Readme updater
on:
  schedule:
    # Runs every day at 9am UTC
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: install python dependencies
        run: |
          pip install -r requirements.txt
          python readme.py    
      - name: Commit file changes
        run: |
            git config --global user.name 'zenith110'
            git config --global user.email ${{ secrets.EMAIL }}
            git add .
            git diff --quiet --cached || git commit -m "Update README" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
